"use client"
import Link from "next/link";

import { Metadata } from 'next';
import Button from "@/components/common/Button";
import { BiArrowFromLeft } from 'react-icons/bi'


export const metadata: Metadata = {
    title: 'Next App',
    description: 'Generated by create next app',
}

export default function Home() {
    return (
        <div className="w-full h-full">
            <strong>主页</strong>
            <br />
            <br />
            <ul>
                <li className=" from-slate-50">
                    <Link href={`/test#id`}><Button icon={BiArrowFromLeft}>test</Button></Link>
                </li>
            </ul>
        </div>
    )
}
