"use client"
import Link from "next/link";

import { Metadata } from 'next';
export const metadata: Metadata = {
    title: 'Next App',
    description: 'Generated by create next app',
}

export default function Home() {
    return (
        <div>
            <strong>主页</strong>
            <br />
            <br />
            <ul>
                <li>
                    <Link href={`/test#id`}>/test</Link>
                </li>
            </ul>
        </div>
    )
}
